const MEMBERS={Hugues:{c:'hugues',i:'H'},Caro:{c:'caro',i:'C'},Sacha:{c:'sacha',i:'S'},Jules:{c:'jules',i:'J'}};
const seed={events:[{id:1,title:'Réunion parents',date:'2026-09-15',time:'18:00',who:'Hugues'},{id:2,title:'Entraînement vélo',date:'2026-09-16',time:'18:00',who:'Jules'},{id:3,title:'Dentiste',date:'2026-09-17',time:'16:30',who:'Sacha'},{id:4,title:'Dîner en famille',date:'2026-09-18',time:'19:00',who:'Caro'}],tasks:[{id:1,title:'Ranger la chambre',who:'Jules',done:false},{id:2,title:'Sortir les poubelles',who:'Sacha',done:false},{id:3,title:'Appeler le garage',who:'Hugues',done:true}],groceries:[{id:1,title:'Lait',done:false},{id:2,title:'Œufs',done:false},{id:3,title:'Tomates',done:true},{id:4,title:'Pain',done:false}],meals:[{day:'Lun',title:'Pâtes pesto'},{day:'Mar',title:'Poulet, légumes rôtis'},{day:'Mer',title:'Tacos maison'},{day:'Jeu',title:'Saumon, riz'},{day:'Ven',title:'Pizza maison'},{day:'Sam',title:'À décider'},{day:'Dim',title:'Lasagnes'}],recipes:['Curry coco express','Bowl saumon-avocat','Orzo tomate-feta'],messages:[{id:1,from:'Caro',to:'Toute la famille',text:'N’oubliez pas le pain en rentrant.',read:false,created:'18:24'}]};
let data=load();let active=null;
function load(){try{return JSON.parse(localStorage.getItem('havoo-v0'))||structuredClone(seed)}catch{return JSON.parse(JSON.stringify(seed))}}
function save(){localStorage.setItem('havoo-v0',JSON.stringify(data));render()}
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function av(n,mini=false){let m=MEMBERS[n]||{c:'hugues',i:'•'};return `<span class="avatar ${m.c} ${mini?'mini-avatar':''}" title="${esc(n)}">${m.i}</span>`}
function fmtDate(x){return new Intl.DateTimeFormat('fr-BE',{weekday:'short',day:'numeric',month:'short'}).format(new Date(x+'T12:00:00'))}
function render(){const now=new Date();document.querySelector('#app').innerHTML=`<main class="backdrop"><div class="shell"><header class="topbar"><div class="brand"><div><div class="logo">HAVOO</div><div class="tagline">La maison, ensemble.</div></div></div><div class="top-right"><div class="weather"><span>☁️</span><div><b>Namur</b><div class="secondary">Maison</div></div></div><div class="clock"><div class="time" id="clock">${now.toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})}</div><div class="date">${now.toLocaleDateString('fr-BE',{weekday:'long',day:'numeric',month:'long'})}</div></div><div class="family">${Object.keys(MEMBERS).map(n=>av(n)).join('')}</div></div></header><section class="grid">${agendaCard()}${tasksCard()}${groceryCard()}${mealCard()}${recipeCard()}${messageCard()}</section></div><button class="voice-fab" onclick="voiceModal()"><span class="mic">🎙</span> Parler à HAVOO</button><nav class="mobile-nav"><button onclick="openPanel('agenda')">Agenda</button><button onclick="openPanel('tasks')">Tâches</button><button onclick="openPanel('groceries')">Courses</button><button onclick="openPanel('meals')">Menu</button></nav></main>`;if(active)openPanel(active,true)}
function title(t,n){return `<div class="card-title"><h2>${t}</h2><span class="count">${n}</span></div>`}
function agendaCard(){let rows=[...data.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,7).map(e=>`<div class="row"><span class="dot" style="background:var(--${MEMBERS[e.who]?.c||'hugues'})"></span><div class="grow"><div class="primary">${esc(e.title)}</div><div class="secondary">${fmtDate(e.date)} · ${esc(e.time)}</div></div>${av(e.who,true)}</div>`).join('');return `<article class="card agenda" onclick="openPanel('agenda')">${title('Agenda',data.events.length)}<div class="rows">${rows}</div></article>`}
function tasksCard(){return `<article class="card" onclick="openPanel('tasks')">${title('Tâches',data.tasks.filter(x=>!x.done).length+' à faire')}<div class="rows">${data.tasks.slice(0,4).map(t=>`<div class="row"><span class="check ${t.done?'done':''}" onclick="event.stopPropagation();toggle('tasks',${t.id})"></span><div class="grow"><div class="primary">${esc(t.title)}</div></div>${av(t.who,true)}</div>`).join('')}</div></article>`}
function groceryCard(){return `<article class="card" onclick="openPanel('groceries')">${title('Liste de courses',data.groceries.filter(x=>!x.done).length+' articles')}<div class="rows">${data.groceries.slice(0,5).map(t=>`<div class="row"><span class="check ${t.done?'done':''}" onclick="event.stopPropagation();toggle('groceries',${t.id})"></span><div class="primary">${esc(t.title)}</div></div>`).join('')}</div></article>`}
function mealCard(){return `<article class="card" onclick="openPanel('meals')">${title('Menu de la semaine','7 jours')}<div>${data.meals.slice(0,5).map(m=>`<div class="meal"><div class="day">${m.day}</div><div class="primary">${esc(m.title)}</div></div>`).join('')}</div></article>`}
function recipeCard(){return `<article class="card" onclick="openPanel('recipes')">${title('Idées recettes',data.recipes.length)}<div class="recipe-chips">${data.recipes.map(r=>`<div class="recipe">${esc(r)}</div>`).join('')}</div><p class="hint">Des idées simples à garder sous la main pour préparer le menu.</p></article>`}
function messageCard(){let unread=data.messages.filter(x=>!x.read).length;return `<article class="card" onclick="openPanel('messages')">${title('Messages',unread?unread+' nouveau'+(unread>1?'x':''):'À jour')}<div class="rows">${data.messages.slice(-3).reverse().map(m=>`<div class="row"><div class="grow"><div class="primary">${esc(m.from)} → ${esc(m.to)}</div><div class="secondary">${esc(m.text||'Message vocal')} · ${esc(m.created||'')}</div></div></div>`).join('')}</div></article>`}
function toggle(type,id){let x=data[type].find(x=>x.id===id);if(x)x.done=!x.done;save()}
function closePanel(){active=null;$('.overlay')?.remove()}
function openPanel(type,rerender=false){active=type;if(rerender)$('.overlay')?.remove();const meta={agenda:['Agenda','Ajouter un événement'],tasks:['Tâches','Ajouter une tâche'],groceries:['Liste de courses','Ajouter un article'],meals:['Menu de la semaine','Modifier le menu'],recipes:['Idées recettes','Ajouter une recette'],messages:['Messages','Nouveau message']}[type];document.body.insertAdjacentHTML('beforeend',`<div class="overlay" onclick="if(event.target===this)closePanel()"><section class="panel"><div class="panel-head"><div><h1>${meta[0]}</h1><div class="hint">Touchez, ajoutez, modifiez. Les changements sont enregistrés sur cet appareil.</div></div><div><button class="add" onclick="showForm('${type}')">＋ ${meta[1]}</button> <button class="close" onclick="closePanel()">✕</button></div></div><div id="panelBody">${panelContent(type)}</div></section></div>`)}
function panelContent(type){if(type==='agenda')return `<div class="panel-list">${[...data.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(e=>`<div class="row">${av(e.who,true)}<div class="grow"><div class="primary">${esc(e.title)}</div><div class="secondary">${fmtDate(e.date)} · ${esc(e.time)} · ${esc(e.who)}</div></div><button class="close" onclick="del('events',${e.id})">Suppr.</button></div>`).join('')}</div>`;if(type==='tasks')return `<div class="panel-list">${data.tasks.map(t=>`<div class="row"><span class="check ${t.done?'done':''}" onclick="toggle('tasks',${t.id})"></span>${av(t.who,true)}<div class="grow primary">${esc(t.title)}</div><button class="close" onclick="del('tasks',${t.id})">Suppr.</button></div>`).join('')}</div>`;if(type==='groceries')return `<div class="panel-list">${data.groceries.map(t=>`<div class="row"><span class="check ${t.done?'done':''}" onclick="toggle('groceries',${t.id})"></span><div class="grow primary">${esc(t.title)}</div><button class="close" onclick="del('groceries',${t.id})">Suppr.</button></div>`).join('')}</div>`;if(type==='meals')return `<div class="panel-list">${data.meals.map((m,i)=>`<div class="row"><b style="width:55px">${m.day}</b><input style="flex:1;border:0;padding:12px" value="${esc(m.title)}" onchange="data.meals[${i}].title=this.value;save()"></div>`).join('')}</div>`;if(type==='recipes')return `<div class="panel-list">${data.recipes.map((r,i)=>`<div class="row"><div class="grow primary">${esc(r)}</div><button class="close" onclick="data.recipes.splice(${i},1);save()">Suppr.</button></div>`).join('')}</div>`;return `<div class="panel-list">${data.messages.slice().reverse().map(m=>`<div class="row"><div class="grow"><div class="primary">${esc(m.from)} → ${esc(m.to)}</div><div class="secondary">${esc(m.text||'Message vocal')} · ${esc(m.created||'')}</div>${m.audio?`<audio controls src="${m.audio}" style="width:100%;margin-top:8px"></audio>`:''}</div><button class="close" onclick="del('messages',${m.id})">Suppr.</button></div>`).join('')}</div>`}
function showForm(type){let body=$('#panelBody'), members=Object.keys(MEMBERS).map(n=>`<option>${n}</option>`).join('');if(type==='agenda')body.innerHTML=`<div class="form"><input id="fTitle" class="wide" placeholder="Événement"><input id="fDate" type="date"><input id="fTime" type="time"><select id="fWho">${members}</select><button class="add" onclick="addAgenda()">Ajouter</button></div>${panelContent(type)}`;else if(type==='tasks')body.innerHTML=`<div class="form"><input id="fTitle" placeholder="Tâche"><select id="fWho">${members}</select><button class="add wide" onclick="addTask()">Ajouter</button></div>${panelContent(type)}`;else if(type==='groceries')body.innerHTML=`<div class="form"><input id="fTitle" placeholder="Article"><button class="add" onclick="addGrocery()">Ajouter</button></div>${panelContent(type)}`;else if(type==='recipes')body.innerHTML=`<div class="form"><input id="fTitle" placeholder="Nom de la recette"><button class="add" onclick="addRecipe()">Ajouter</button></div>${panelContent(type)}`;else if(type==='messages')voiceModal();else body.innerHTML=panelContent(type)}
function id(){return Date.now()+Math.floor(Math.random()*1000)}function val(x){return document.getElementById(x)?.value.trim()}
function addAgenda(){if(!val('fTitle')||!val('fDate'))return;data.events.push({id:id(),title:val('fTitle'),date:val('fDate'),time:val('fTime')||'00:00',who:val('fWho')});save()}
function addTask(){if(!val('fTitle'))return;data.tasks.push({id:id(),title:val('fTitle'),who:val('fWho'),done:false});save()}
function addGrocery(){if(!val('fTitle'))return;data.groceries.push({id:id(),title:val('fTitle'),done:false});save()}
function addRecipe(){if(!val('fTitle'))return;data.recipes.push(val('fTitle'));save()}
function del(type,idv){data[type]=data[type].filter(x=>x.id!==idv);save()}
let recorder,chunks=[];
function voiceModal(){document.body.insertAdjacentHTML('beforeend',`<div class="overlay voice-layer"><section class="panel voice-modal"><div class="panel-head"><div><h1>Parler à HAVOO</h1><div class="hint">Dictez une action ou laissez un message vocal.</div></div><button class="close" onclick="$('.voice-layer').remove()">✕</button></div><div class="voice-actions"><button id="dictate" onclick="dictate()">🎙 Dicter une demande</button><button id="record" onclick="recordVoice()">● Enregistrer un message</button></div><div class="form" style="margin-top:15px"><textarea id="voiceText" class="wide" placeholder="Ex. Ajoute du lait aux courses"></textarea><select id="voiceTo"><option>Toute la famille</option>${Object.keys(MEMBERS).map(n=>`<option>${n}</option>`).join('')}</select><button class="add" onclick="interpretVoice()">Valider</button></div><p class="hint">Pour la V0, HAVOO reconnaît les demandes simples contenant « courses », « tâche » ou « message ». L'interprétation IA viendra ensuite.</p><div id="recording"></div></section></div>`)}
function dictate(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('La dictée vocale n’est pas disponible dans ce navigateur. Vous pouvez écrire la demande.');return}let r=new SR();r.lang='fr-BE';r.interimResults=false;$('#dictate').classList.add('listening');r.onresult=e=>$('#voiceText').value=e.results[0][0].transcript;r.onend=()=>$('#dictate')?.classList.remove('listening');r.start()}
function interpretVoice(){let t=val('voiceText');if(!t)return;let low=t.toLowerCase();if(low.includes('course')){let item=t.replace(/.*(?:courses?|course)\s*(?:[:,-]|de|du|des|le|la|les|un|une)?\s*/i,'').trim()||t;data.groceries.push({id:id(),title:item,done:false})}else if(low.includes('tâche')||low.includes('tache')){let item=t.replace(/.*t[aâ]che\s*(?:[:,-])?\s*/i,'').trim()||t;data.tasks.push({id:id(),title:item,who:'Hugues',done:false})}else{data.messages.push({id:id(),from:'Hugues',to:val('voiceTo'),text:t,read:false,created:new Date().toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})})}$('.voice-layer').remove();save()}
async function recordVoice(){if(recorder&&recorder.state==='recording'){recorder.stop();return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{let blob=new Blob(chunks,{type:recorder.mimeType}),reader=new FileReader();reader.onloadend=()=>{data.messages.push({id:id(),from:'Hugues',to:val('voiceTo'),text:'Message vocal',audio:reader.result,read:false,created:new Date().toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})});stream.getTracks().forEach(t=>t.stop());$('.voice-layer').remove();save()};reader.readAsDataURL(blob)};recorder.start();$('#record').textContent='■ Arrêter et enregistrer';$('#record').classList.add('listening');$('#recording').innerHTML='<p class="hint">Enregistrement en cours…</p>'}catch{alert('HAVOO a besoin de l’autorisation du microphone pour enregistrer un message.') }}
render();setInterval(()=>{let e=$('#clock');if(e)e.textContent=new Date().toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})},15000);
