const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const members={Hugues:{color:'#1688ff',short:'h'},Caro:{color:'#ff4291',short:'c'},Sacha:{color:'#20b969',short:'s'},Jules:{color:'#f39a1f',short:'j'},Famille:{color:'#7048ff',short:'f'}};const now=new Date(),iso=d=>{let z=new Date(d);z.setMinutes(z.getMinutes()-z.getTimezoneOffset());return z.toISOString().slice(0,10)},plus=n=>{let d=new Date();d.setDate(d.getDate()+n);return iso(d)},today=iso(now);const seed={events:[{id:1,date:today,time:'09:00',title:'Réunion technique',who:['Hugues']},{id:2,date:today,time:'17:30',title:'Sortie vélo',who:['Jules']},{id:3,date:plus(1),time:'16:30',title:'Dentiste',who:['Sacha']},{id:4,date:plus(2),time:'19:00',title:'Dîner en famille',who:['Hugues','Caro','Sacha','Jules']}],birthdays:[],tasks:[{id:1,title:'Préparer dossier bornes',who:'Hugues',done:false},{id:2,title:'Organiser le week-end',who:'Caro',done:false},{id:3,title:'Sortir les poubelles',who:'Sacha',done:false},{id:4,title:'Ranger la chambre',who:'Jules',done:false}],groceries:[],lastShoppingReset:'',meals:[['Lun','Poulet curry, riz'],['Mar','Pâtes bolognaise'],['Mer','Saumon, quinoa'],['Jeu','Wraps poulet'],['Ven','Soirée pizzas 🍕'],['Sam','BBQ'],['Dim','Risotto champignons']],messages:[],dismissed:[],favorites:[]};let data=(()=>{try{return JSON.parse(localStorage.getItem('havoo-v8'))||structuredClone(seed)}catch{return structuredClone(seed)}})();const save=()=>localStorage.setItem('havoo-v8',JSON.stringify(data));function sunday(){let d=new Date();d.setDate(d.getDate()-d.getDay());return iso(d)}if(data.lastShoppingReset!==sunday()){data.groceries=[];data.lastShoppingReset=sunday();save()}const recipes=[{id:'pasta',title:'Pâtes crémeuses aux champignons',time:'30 min',img:'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=700&q=85',ings:['Pâtes 400 g','Champignons 350 g','Crème 200 ml','Parmesan 60 g'],desc:'Crémeux, rapide et parfait pour un soir de semaine.'},{id:'bowl',title:'Bowl méditerranéen',time:'20 min',img:'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=700&q=85',ings:['Quinoa 240 g','Tomates cerises 250 g','Concombre 1','Feta 160 g'],desc:'Frais, coloré et facile à adapter.'},{id:'salmon',title:'Saumon rôti miel citron',time:'35 min',img:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=700&q=85',ings:['Saumon 600 g','Citron 2','Miel 2 c. à s.','Pommes de terre 800 g'],desc:'Un plat familial simple avec peu de préparation.'}];function lion(n){if(n==='Hugues')return `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="#6e351b"/><path d="M20 30 13 12 34 22M80 30 87 12 66 22" fill="#a85c29"/><circle cx="50" cy="51" r="31" fill="#e7a54e"/><circle cx="39" cy="47" r="4"/><circle cx="61" cy="47" r="4"/><ellipse cx="50" cy="61" rx="15" ry="11" fill="#f8d69a"/><path d="M46 57h8l-4 5Z" fill="#432418"/></svg>`;if(n==='Caro')return `<svg viewBox="0 0 100 100"><path d="M23 35 15 17 36 27M77 35 85 17 64 27" fill="#d88b3d"/><circle cx="50" cy="52" r="34" fill="#e9a650"/><path d="M34 44q5-6 11-1M66 44q-5-6-11-1" fill="none" stroke="#3b2417" stroke-width="2"/><circle cx="39" cy="49" r="3.5"/><circle cx="61" cy="49" r="3.5"/><ellipse cx="50" cy="62" rx="14" ry="10" fill="#f9d89e"/></svg>`;if(n==='Sacha')return `<svg viewBox="0 0 100 100"><circle cx="50" cy="53" r="37" fill="#bd6c2a"/><circle cx="50" cy="54" r="28" fill="#efb15c"/><path d="M29 37 21 23 39 31M71 37 79 23 61 31" fill="#efb15c"/><circle cx="40" cy="50" r="4"/><circle cx="60" cy="50" r="4"/><ellipse cx="50" cy="62" rx="12" ry="9" fill="#f8d69a"/></svg>`;return `<svg viewBox="0 0 100 100"><circle cx="50" cy="55" r="30" fill="#f1b65d"/><path d="M31 40 24 27 39 34M69 40 76 27 61 34" fill="#f1b65d"/><circle cx="40" cy="52" r="4"/><circle cx="60" cy="52" r="4"/><ellipse cx="50" cy="64" rx="11" ry="8" fill="#fae0ac"/></svg>`}function avatar(n){return `<div class="member" style="--c:${members[n].color}"><div class="member-avatar">${lion(n)}</div><div class="member-name">${n}</div></div>`}function eventColor(e){return e.who?.length===4?members.Famille.color:members[e.who?.[0]]?.color||'#777'}function eventsOn(date){let a=data.events.filter(e=>e.date===date);let md=date.slice(5);data.birthdays.filter(b=>b.date.slice(5)===md).forEach(b=>a.push({id:'b'+b.id,date,time:'',title:'🎂 '+b.name,who:['Famille']}));return a.sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'))}function weekStart(f=today){let d=new Date(f+'T12:00:00'),x=(d.getDay()+6)%7;d.setDate(d.getDate()-x);return d}function dashboardWeek(){let s=weekStart(),h='';for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i);let di=iso(d),ev=eventsOn(di);h+=`<div class="daycol ${di===today?'today':''}" onclick="openCalendar('day','${di}')"><div class="dayhead"><b>${new Intl.DateTimeFormat('fr-BE',{weekday:'short'}).format(d)}</b><strong>${d.getDate()}</strong></div>${ev.map(e=>`<div class="event"><span class="event-dot" style="background:${eventColor(e)}"></span><span class="time">${e.time||''}</span><span class="label">${esc(e.title)}</span></div>`).join('')}</div>`}return h}function currentRecipe(){return recipes.find(r=>!data.dismissed.includes(r.id))||recipes[0]}function render(){let r=currentRecipe();$('#app').innerHTML=`<main class="screen"><header class="topbar"><div class="brand-wrap"><div class="brand">HAVOO</div></div><div class="family" style="display:flex!important;align-items:center!important;justify-content:center!important;min-width:0!important;overflow:visible!important"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAnYAAADdCAYAAAA2ED/9AAAAAXNSR0IArs4c
6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAP+lSURB
VHhebP1ZsyU5kueJ/RSAmZ3trr7HHrlWZa3dxa6u6mZvIk0OKU2+kiL8NPVt
+EyReaEMRWZIke6pqa7MrsrMyIyMjNV3v373ezZbAPBBFXaOR/VxP/fYAoMB
ClXFHwqFQn7wk3+dM5k+QQSyODKQYfc3g2QQMoheEBGcryyFQ7ynqmuqUCEi
pAgpC82kwYcacR6c5j3ETM5QNRU5JYYhAoL3HnIm9ltq76mroK9LEXLCOS1D
ihHIeO8YImyHxJAFCR4Roe8HRDLOOSrvmVQVTVVRBY8Xz3RSM22mTCcTpnU1
ltmJ1jinjP4TUhYimZS17uIcz54949mzZ7TbLT44nAjeCc4LLme8OGazCQ8e
3OPRo8dMZoek7EAEEYyyGTskZ6W4jBQvaXZHmrY8wZjPOxeypZNdSkHbK8aB
tmu5W97x9s0ZF2/fEocWcZlu09N3PVUleAdp6Ekp4UQQD7XzNN4p/byQYqTf
tkybwHRWQ0rEPtLMjrj//kecPHiMZKHyUwg1CdA/WpZshZOxoFbTnPUaxmuA
iF4RybiSRgQpdbV2gTzey9naEeVbyxDZJ5rY+60cAuTS/mh+ef/95SuCK3S1
dtHr+i5XXiFiz+41hr5l/yWWi5Y927e8uzwhWe9jZXECWgp7Dzu+KmmyPlje
+E8+7/DZXpso7UrtSjlEr71T9EK9clwoYcTIu1NNsfu7OyxtpxcErb+2k9Wj
FDTnUgrljUIrS7CX87uforfsKzmN9NrnMSWgELOQcmFXfWNCiAliUr2lr9yT
yVLmoiPGJ61chV+N58RI5EXb0iE4B56ME62nM34PZCDhJeEE/HicECl57lU3
CwnISUhS6qJ6LJfC2cdJxovgwbhpxxU9nj47NqliQ6AVxyBCNvlKhaqi0pDs
aW16TfPup7zY2sLkRdA6+FwoDi5nHFnvlzQ5jTrTW9mDywSndAwSCaL1cLKj
o/IUJKdtG5zH50wgUpHwEhE0b7y3Eih/JHFEPNvsWLoJ6xzo8SRrc3JGUibk
hMuRhszERRofCU7bC4GUk5bLKa+1yXMzVFzGCZsUSDmTs+mtkq+Ry5k8qz4B
cWhfU+gmGZFMkEwtiUYitSSrm/JQSQvabtF7etFvFEcUx4AjZkcUT0SIOIYE
ycokgDjBO0fKEIek/WROWNMRE/TdwNBH4hDJKY1yqm1p/Dryxr4OKfp9p2Md
2dpaUwYBEb2m9VWZKbyDZKIIUYQBrVOPZ8hCximvOhU6EUG84CrBN4JzDnFO
5bCoA4TkPBmvfA9A0nYqpc/6q7Jlcp6KdCScMzl0pX9RGdo9Z5JRGoid0sti
uinv9LBkk59sOr7omb3HBfDHJx/+Tc5JH3RaARGtpEqfghkpxDAGVaZVgXMu
QeyJ/Zah3TC0G/quJfZbUuqJfUfKkZwj0UAaZHzwBOfIOSs4Ch7vhDj0QGbS
1HgvkLIyCTuFLoDzWpCYhagFHesQc2ZI0A2Rddux3Gy4WS65uFtydbvk/OqG
i+srbm7vWK6WtG1LTAND7Ojalq7vyNnKWAW8d7jg2G62vHz1guXqDnGCc54Y
IzGqsnJeAdww9AxdhwNmkymT6YSU0tgI2hDWXFIOTQBL5zEKgB3Yz37noOcl
T20jV0CFV5rGmLg4v+Ds7DU31+dsVkuGvsM5qCqPdwFfBTKZYRjIKaK8px2+
APPphKPDGdNpDRlSTHjnRsaqmprpYkbTVPTbDXcXb4FMM51rmxgv7X/ke9dU
DZebhUgljZ5nCrOXNLu8Cg12dDKlUNKIipKzvEqiQrdswlTqvffg+N4C+PeI
PpatAITdb8lbf53TF5b2sawREZLJYCITrTPKImTnUNay8o0129VBxAYNpRzs
51/Ko733CKrtWi6F+D7tx0PLx67vqis4Z7qi8NseLQUZdcbIj3t5WDb2zN57
LG1ptzEve965EdLupUdlf//5scyajyv1LQqxKEsxOhtnRBTAxQQx74ZfaVSk
44vRVrFyFv4r791vg/00dr6rX8lql5cW2vIY31eeyzgDeVpi6wAl2W/GW+dU
gKJy9E6+sgG0CNqJZ0fKjoRT0CIqCAJk5xjw9DjSWEHtHLMIiLM+QysyyrDR
VX/fHTRZV2RphSyQ7NmRYHYdo+u7fFuoYvVRYSWL074gC32CIcGQDZRnpb4D
JBfAkUbwIRjdyHgiLkckDfic8ERyzmgXpKDTEwkpUuVIIFITqbM9twfMFXSC
dwrSPYngMpWAdxmXS1taXa2Ohd9358r73oMv8mF6whAhgUwliZASpIjf708K
3TM40xflm6wtk4GfJJ4hqwGmHxLJBjQgpJQN1AFknDhCcHinRpkUEykq6CsA
RdD3mITuc/Wuzrva2lWt9w7H6PWxrQ2k6tfRI3RZaLOzr6fNej0hZGd5iNHT
O1wQpHJIcPoewzWBvAPGkiFqO1UkfOxxXYfb9riuJww9ru9x3YDrI67rcW2H
324J7ZY69tQ5EiQpH5f6FTbe14fjcdEdRicb/45fESS9OzAqbexElZw/OX3/
b7zTMUvKqKqwt4oNOXLeKX0RZQzNbKf4VCwTGIBTpkv0/Zau0+9ms6bdbhna
lrbd0rUtKfaa3kafKUUFVps1ITjqUBG8ImknhgntPMaojAeknOljYogRESGY
FU6cw3lvSN2pohoSXYpsh46buxVvr244u7zgzfk5b96+5c35Ba/eXnK72TB4
QeqK7NQqud4sef3iNdvNFu8dwXtVgk7flaKNpLwjxoFus8XlxNHxAc55soE7
pVmhobaeWmwYrTbaWkUq96w4JYOShzWmoCAcceUGznu22w3PvnvGzdUV3XZD
125oNxtyBu8Dpw9OODo9RJywXW/ptr2CkJwQJ6Qh09SBw4Mps0lFjpmYIl7U
ujmbTZnN5kyamty33Jy9ZX19ydCvWRwe4eqJWkCKlW2v/FjHjTHzjp/3zo0a
hS+xUd1+JzLeK8p7j0g7Ram0FDFAavnvOhT9Hd+lpbC0mm7/3u6ZUlYrfLkv
O0XCKLylvAZSnCOTqeuA8x7xjkTG1xWhmfDV81d89e13NJOG6XxC8AFSsYgo
z/HOu3c/u3KUOulp6STLtVw6iJImi0IBUbkqeY2KZ6yT8T12fW/wV9KVTkuv
qUmlHI/pxvQFLGphpORf0jgxK2Shq4HKwkFjGa3rsDJgaaym2gGRVeFL0W9m
nY+ZKGqx045gZ40y4uzqY18Frrs6F12G0QWzyumh/tt/ZvyUDAFnYJ4CzooF
ShTcWbWMN03zG4c6s+R4l0erYClHAqKplCTFQqMdYJ89LYGWim0KDHgGHB1e
O0jLKGEvH787mdnxVPkaYxX+suN35Eh2DKrV0Hy0nU3OxzZEe2BxpcdRUGKA
LmUFdGp1skG/IUsxYJJhB0JSNB4340FWa4uCt4RIQpKCFcmJQMLniE8DdY7U
uaehp84DgYTLabSwZ8tLxKxVZrHyToFDTWTiIpVEtTplSNZGxfovzmTRau9Q
66Y3a6WCVAWfIScDmwPB2rmNwmZwbAfHJjrawdNFBcHinfGA0iqJI5lFMiZh
iJmYEinawCBn4qB0i1FBcU6ZGDNdN7DddnTtMM6o7XqsAkKsn9pn/MK676Tb
GwiYbGZ0sKUDksyQFaxHA299hi4LXRL6LAx71nfDgjvhErMBBYcL7/KupERF
pHGJWiI+D/g8UEmiZsAPHWxa8qaDLpLanthFUjswdD2x68n9gPQD0nX4oaWK
HTU9gaQyaAOrXYl2FNhpCaX3OIORQWIi9xE3RHxKOlDIasFWy6ZaVEUEf3rv
o78JwY8EVFCgNzFQJ9YJCQrockbTeG8j5b3pW1Ew4bx2VM57NXMiZmZO5KwC
FeNA1yrQ67st7WZNu10Tuy05tgx9y9B1pNgrYEzKTF6ydoqiHZt4D97pdEPO
eCc6GsvgnSd4r2C0kDELIQSqUFGHQB083jvIOi2ccmbImU0/cL3c8PbqlreX
V1xeXbParNis18QhIqKgcWfVU1O+CwEfPA6nSN8LB7MZk8mEbMq+NGVRMuyZ
ovdvqkJINpep9BvTjL2xnpYOzRUridE8MXB3d8vy9o7tdgs5U1UeEUe77akn
NU3weHHEIdJ3HU7UIudEcBmqEKicI8dE3/UM3cBkNmFxcMBiMSUPkc1qTbvZ
EIctVS3EbosgVNMDfDXRcu4PFo0W7PcRY+e8f66/u3Rms7F7Srhys/BuAW47
i5LStfD5/nkBO7vCaNmU31W5WrlsOmWvEtrPiMmLXRdnJn/71brvgAfFOpeU
l/u+Z71dI5WjmjX0KfPdq1f8/T/+I69fvmA6c0wnjlA5fAj4qkLE6UChDLRU
FMfyaZH0XXai39H8UW7vzhFUTgyR7dqj1N9+9yyPOv4TU+bYtIbeU/4uTSMK
ejB9sv+OIs+ma0b6Frob7QGwaZOiBLU9C8Aqz2i+xTqbhXcsoSJ+BMUZmy4p
QM9oIk7IBlwLDUtVBRsrWv3L8Ti9KhBMDkuaUqZ9GdBBiJHeaL8/MBmBgd2z
2u3AoxWtlG2fbuy1T5li8kZjDAyp3vdEPL1ztAbkOtFpx87AXd7rFwrYLp+i
0/Sdu+t6pRTSSm69bKnfrlaMykEHFXtpCoH2+hjt7PXdycB5LFrS2rJ8s70j
JXUPyglSUuCjRgG17PX2jUlBwZCEPjm6rPlIBp+hyomQk1rrkoIyl5K64ZjV
tIBvGDtM1fDZwEpSoOclU+fERCK1AfFkAIZ3VTzZQE9wCg59Bp8zlWQqMiFH
tTaSicmzHhy3fWDZezaDo4tClxx9EmJUYJTEk51a6VJWoJfRAadzDu/MzWgc
ICg/Y7M2Q5/oewU1aqn73gCv/BNtPZHSiPrRQZwOVA1aqYxqQ1u9zejkdu2V
zNo8gFoXsxCdTsMms0YXna2vK3hhT4bt670aYgTBJ6hTosmROul0fcgRHxP0
A7mLpCGrq1lM5p5hINJqkEzpeW8gfBgIsSOkXvNy2r4Z7V9VJr7/MSKJg5SJ
3UC3bunXW9K2I25bUtcTty30A2L8lJMCb3//wcd/o3PKAqKm+FFg7IXFj2Jf
YSjRvVn4zMgqpRMzJhZR8GMoUjSRvUv0TVlHRDkNar2LA46Il0waBuLQM/St
Wv7aDV3b0vcdbdvS971Og6bIMERiVH+JlBIpKkAj6whWREFSjtF8A5TpKifU
lacOTv36ggJRbEqmHQbW25blasNqvaEfyrvjTgBt2jpnZWpVgGrNq5zHk5kG
z8FCrWJGVKVZViWtAq8IPZWpZwN82hrG7VklXK16o76zvIqlYGeNijGyXa/Z
rDds1hv6rh/fEYdIPwzEGOm2Hf1W74lZQ4d+MKukow6eNET6bsB5z/TggHv3
H+K9qAV2o3mT1bfRe6HbtuTkmR3do5pMydoFWxl3ne/ID+O3pNE20gt2bseq
+NTEvrtvvyUDS1OOVZj0fi6duKmf8fnyKQUY75eORr9jOS2NWJkKsCtpSqJS
7rE4qHUqVIHshc+++JKvvn3K+fUlV7fXPH/9iq+++Ya3F2eQOio3kIYl27sr
unaNC0Jd12oFLsX9Ho3eVap6PNZIyrndH8u6S8doQSv1t+dElC9l1/OIuSUU
C2R5zzt02AMpVojv0dHKPpb83U9Jq9hgR9uS1+53rx6lTcapQ5NXN6JgTTPq
Pf2KsFcDK1cBYoot1T9NdFjrzGeufMP3zsdO0V6t5zaY+35V0Htagx0txWg+
PodSSutaziyHnZli/ypeoHLqr+RF76VsPlbspmOTdZBJdJZDaWdZG1DHNFMp
/MgXZiWxJDtdZ6elzLvyscvQDkdZk7F70bYZfZVMK0rRjmLWLutcy9QiBfRp
PZNZcoZsfmQIQ1bw1mevU3jJs02ONjm2ydMmR5+dAj4bXxc/QE8iGKDbb9NS
u5Ek5kOXsvqixaRAQPMz/rFKplK+EYgasDHLouad8fbeYqnzSX35YhQ2vWM5
ODaDY0il/Xe8pPYBJW4Wr9Y6A3kZBbEqKkJwQvCO4BzB7QwHDvUfTEkBXTZZ
3/Hb7nhs4oya5Sh8YdYoK9sofNbG47n1r6UCpf1Hk4dNtY48UYhvz5fBSKkX
ZrHNKeq1KDBkXEzIkMhdInWR2din/XbRVLUaXmdFlc+TiI6SNhz73Biw6UcC
Vmn6it02t6lqMYtMfyEycMeCdizd+YMcYgM3UDsB3JM5Kh4J/WRHBNpUKPU0
A10mx758R/8m6x+GMroXYK+OMeqhBkrKfFH+RuJbA2X95x5xynaMlLVNKUxS
oPklHbzxPoCVX6WXkxYdgDHXomOahDVkAmHTv6WqSlP1TS4UCHZgKXOLZIM0
Q4p452jDo5KMiRzotWMSRm6BB2iZt+kZamDkNqO2Pda1hDwTn0DRQTvHd7pQ
oNJFZh4YSKZx/dO+ODDj8BXZia2kZkxQ0rqY1WmVXLKei0bbc1yMFIiG11Lx
2jWtTIiGeLAer1mtVopsGu3bFYr+q6jazva7QbnhGpS4UToNx2ZTD0JeCes7
pasl7c004qJD8yaGi+OECqOTo45Oj3h8GDB5euX3F6ck2OHDx7BkaLSKXYds
8MHPPjBHzA5PCUlTKmzp+yV94zFlENMAxTwvX9b+W9MbEfKGyMfGeYot5SXC
v9pmlFoSrrysQd36qi80/itJNkvsqVRPjdRNQuOFOtUUfyAE22rjLAdep6fn
fEPv/w119c3+EqtckMc2LZb+r5lWgmHtXC6CMwqz6RumC2OOTh8yOPHH1JVc
1JSS4RQgFwpo9V21Bu7Gu8fZUv2Dj0sn6xurnvtoUpNLYZGnzJgsffHmElR2
/ZdOln5xhfpyXhagOJYifIx5VdqsVdQ7SfKhJUVez+BtUcZSWNKWBmi5GeDK
utA7am9DNQB3JnvmVhblneN51mBnhgIHFFQZtSjY8e2/4a9/JRPsk3fRrueb
Bit/nTeFk+oL9eOt7QcO42tb911eEpDlbqIo8uBdQxssjrTj1ZLy0H1tf2KY
uFSJbWQuRFcjYaAcfFJ6exUd1mGSg6jiezVvSQYZchKKiNjal1lj4RjKZU5x
7qLtYFk7Y8wg3aZJi35jnY9e34sgwF2QfnfFxBi7argXafDArY4ojCBFUwH+
UrPOAJQA2tZ6Zmycm02X8cue9YpsM2BoSyASXlEJA5dPFFJIoiCO4daEM2Tm
SHBZhA2WftFDwRvC03seefAe49UnhwcqQpEH0jOk0QNDkoqnVI2JrC2076rT
MkOMREHnSolW19W5GgvD0mKbLMKoLWpEkx2orgjoCbY5x77FHnTf1l24F/bq
3CF/tHBqd6VPb2cQWXIOZU155T3UsKnqAuVFIDYYCyPA65sg58uCV1UK2jhe
RGoJelCGolMGJjIQB0yzjtiCGxCwyrMWEtjNLdBpvEIoroIDNgPidQP5H6AF
Eldb7N5O5Yb8VoG+fEf/u8Ly5Lxao5OMJipE+ftsZGvy6u/9ymCYgxeCGetp
e8swEsXTOSs6CbbqqECVMj6DluHoC2ejbM013HeP+VMzJlYGBHB+8B0MSeEC
kYhcnjvCSGQMrR9RJxaoioBUiSngaHtcd7hqoo2ZtZ9ordVLlqUpFbFnG0Vj
VopnHhdrCDgxVFVgdm0ZlY5ajLHsynvP3mP2eIAfKXqJOlUnFodk2qM4thLE
QodFY20QXYWkawNIk6nnER0ZS4C7XbL5cUl5+cXrJdrXACF68IQE8MwUDcV8
8MpkuHq7QXtdkvV1DSTCUPfc3N1BikyDTWLxYzZdMJ0PmdxcEQzmTKf1bx9/
ozl5TlCpK4rnAuIC0zqGnJmfnyfxYP38c3cQEBpVG1Kk7fxU0zzjB213hTjo
XcSj9fs2Gg2nhfeK1nuf7K9oVzfZ2l7T7k1qgETHL29n6FZSK382smaErEVj
9rRlGPHetNyeX3L1eqOb188483bM7pOF+zkqMMUH4ScBxoPc9dzPIVpUDuE8
4H5/IgffPpTTk8+ADcnEsB8idCiavllxzN6QctsfcruWsE6FKKVc6OT8V8yl
BeHiDihagJd13F7e0uOkdPTY5pmSozaC6i1wlpTdIA1vjSXt+hntETLTp2Pd
/dIrk7UlhYxmdmrc7lnF1QZl4dtsZh1PIygzjqk0dthn58UbDhEpzNNH4xEK
z5w2Vb0GTAgG/33iJ21QLvqjLfsZWL9uJVhN6FYgF3GSRxXfo4WQav/WHewU
uqgfafFxPz2UGCXA9vsGcqKTyXnWL6R1c0FRqx+eZwOUwvTQFmEMTqO7FT3O
/Ki5yM427uldTC6oe/cdV6FxpZOG3Gkk34Kzcv1QlajSd4Hd2XhhAG78n63a
1stT3nXTv61jRVYVS4SciaUQYvY4FScTR8KvdGptIOCOwO+otZAjcCgFkSF9
Qak1dawm6XI6OpuAUkK7BxqRczq60+Xoc9mbJBMEAV3lQiVN8uxV4NH9o4UH
IMPJO/JNvDEFkrEIZKSCoUTW3BgA7lsRhbDbDbNnUhl5imaMcXACeZOpf2/Z
jBq2tKEYn3b3sWCC/S2MoDqWEXaubS1CoDmbR9XmFUf1ufG08JrpX9Vpi3T5
GIGfl19bf6uxm06fQ9D9gxpx4GCgv7GZxqXqSVSu6hA3OlcevSBNjRsfUMfg
k2BFwuzZqLNvmepTDbjmBO5HRTojauTR+LgcOpjJ3udqBJKRxkplzHLXmeMj
dwMDo6+ebDXeShTjw1RFGhRPkZsbwhZ26IIkY1CvzfitfZCzApImTPfF+yck
BzNgXWAoSf3na7KHVpIA0EAEkPfk6MuAKi8KeucIEbNNzi6GNlsO/qu1+X2K
TIMPdmsfSGEcRUsIji/M/0DeOfwXkHsZt1ZVZw6pCoc13o4h5hZt11vWC9XD
F1nz+uCi0wRAmVybasdTUZgYd+cdSp723bc3S3p+46h78fOuJk1TGczvPM4E
dqtTnPHlPFVw2Q6Zei2dJuW4Csmkxmz+ZzJZEpMwu31EnIi9VtyiuPKqaqqm
S1mTGYL6tmc+ckJrpqgi9SVLuUzClL5MaFTTtoXvx377V/T83fPNE/7KrFKd
4BxiXY2I6/+9z72Fstid3mvoOO18TX2zJ6C2G8Tp527D4E2Rp69fMNnX3zN8
7M3XNxcEXMefVOcLb4JwUNOuDgwq6HxGUkRyQNBIp4O17fMqsBkMkN8GGWxk
EGsgLsSF6H8pzxT0pTy6yDYrPRZLexDHGi7LddXV7w5O2O5vmPbrrm4eMvzp
99ycfaaKhQX7MFGuWa9GMti1mWx8ijrGx13VuddOfUwW71GHWbP5O+lA623l
DraFPz4jjKdZH595Ss2KNXrBs72fIy8kzG8RlU6S9HQC96pWi5TnK5Mybo9E
CAKwrzoKsnxuDzjMP1n7TLy1F7Zy/X9ofrom2bWNtPJOq3q6MUWReTAlkCP+
c+lsjBCLQZlutUBlcvULlO5RC2Z2iUaSUxdZCqJmU/MXGTqEhM0xEaZStTBW
+GjfV1ldduzmhRfy+InqvRXfinyIFph4539drX6F94qhHpH3u3YfMeKNVLpY
zNTGbL1dcn4q3yLpTqbRUYXGOi09ZB1ilZDwygdO1G/xBa1um2zZ50DawLrX
LFJgY39ttmzzYGNpWuztkmfdZXmu9ZYrWzOkJLoApEk9BHzBYQuCa0tItCp5
2JFGhnFLE/OLFXG92bNjinpNF9K6qg/JFI3ENuB2PakbiD3Cs6kDHSKXHjwX
gheCEGogh5778bBgIJnW0RSLN8oaB4HQ6Mc7vhcRiD97rfwwCgvChVGWgmFB
3cDLO0A3gV+lDBGlq7cKgMUnE3hJ6X1kHVms4s6qzfYFH9JX0DukK1NkmeTH
KvBsew9q8HTDkJMXleaG/+mmBn6ZFOu5q9Y6OCMjk5xRqg8KQlx0MUtoPloe
wryg5/86+xdUXxqUct4Bls2PKAADzGuMrHQTxnaELLIPSIZATIONFRtDkAPb
cbijj/w5ocEdCG6gEM2cq+F76uWOvUDHO/OSetLvH+YsPqna1GVCoNuWWv9u
xaRg/Wz/tmWoc3syFYLqa9vhm4d9zKTpKMnirBFb9DxGW2yeSgpxuUwxHGYA
T3nfwRkzJJqYf/beOi0z/7MXpPRhbbUVrvKVu1nvjJotTBnuVpwpWLOdJikP
i9lF3NFae7KStAFK3DbLPG8Lb/2MbhZ6J7fHf7aTUr/ON3vAztxswB2+k9de
3DPkurgobl3cDcE9EIOmuRN+4lqFPs/S6sv8ul8SLlFy2DMLadZxZX+6B8a2
CYkJt/Y92kf2bnG6g8E89d68zTlkZ/IeWkAS5q7TVFp4SFMuClsX7S6dzEJl
flldmiIkiqzAnWiTLAl5YqmZqO85YpbSoGx/Lb8MlvQj5SeInEXMZNfsdwY3
Rirzs4hZ3WjpSZ5YtJYMMk2bvo3X8jow5NCeX5JlgGcsnDy6+JDRMku2x3V6
poRS6ydQaWCmROQ0NK7qylDJLu34Nrpm77NtyCnBDGUhgU4DJ49ZfJzkkR0U
nqDJ6Z+lEy5RWLO67bjsCCtzMtVJRpGWX5Jfmg7twmHfEmQhRgfrDTJlF1r+
zZffCLPZUDZFSxsuUj5WmRbXvqPEyNCOTna7yvaN7saJEBqB1qF8a0eXFDhf
4EvbCSs7X13aESvTtmSKrWKbyg/q2VQVVT2hqqbUdZUGVJlil/6kXyOh+EgC
+UiUap11aLkAnImXcnWzYSmFurxDyZtPV3h1QDbya0LXCbPiZuAWOmXfexk1
H7W0nvqbCpxJNANnYjZzmTDDcsjgawV67NBmph20rwaCIxuaWLkKfzeZhM98
m48ky0L3JM4VBPXpeLTvGQjJJ9Wo+qf1djklFY29ip02/IxebVCXpubaDqst
N8NU3Ww5QvAIXZ7OneUzA4aVk9Jk+HXymUknbtZz9jvPbzZstl7ajyjEzHyU
wOl3Nn77dw/uM9EdGY1maKWiqc0khVsJM7kb7bJENpLdg66GWVuKM+3K2pT+
wMz+PAkzGqjPjMwyekqsLuwWuGd3PiRejGl9j3J9rvjnfXmij+I/U5cRnagw
JY5WVnXwztHJaCjxunDTUkdyzFA3367HTBl5u7X37NeSSIedoiY6WNw4s3Th
juRUvyQP0q/QquWrrJcGMUrkeJh38soL24vDD3MtiTMadP4kaFK89t1+NY5z
7ZezOm6tx0bb/G8LdWsNFL823M2sf7X8O6nTQMFAN5gswp4kXZdo1fGcoZ3w
qrUDkEH7HjmpHy1dxMNplaZ3SHlqEgVA89MMzYqfIMn5zCnsypvWB83OIHXR
VuVR7591rgBf4soS5/VCBNsg4bxaGRVmPcLE+5KiKPBFSdHr6fEmPTkaxcyN
iovuhyDGdoo1xkAIgaaJhKammo6ZVmOqakJdVXpVasQdUcUuR8CYtVtXLeGE
Bp1QyPJQnb4TZ29scfFOnXfMhoZZwlzo3qmxdlwGYxcPA1QqMH2y90XooJhk
ZXfhzWmSuzznPYFadss4Ivxm6CAh+jtrwTIzXhulqxDmznXykb/db7IG1daf
BWVfdwLRpT9ZsJR5Z5wU9ARmTlv9UvJ1IWkj7M22i7PLRpzm8o5tFlpz5qO1
Kn/30FfeE5wSK4XBHQYI5s+dFZQ96fP3O8afhT6L1AlQQmR1pIRVp+kUtBa+
zEw8EzV3boYu6JSBCMys9vRFimjjt+RrM2/TdDHskELDInRkgeyETZ+KSusR
I2kxeR42i9pMyeJ3p/alfJD4oZOTwOKESFpeSqbpct7IXFJYWq8YhYcjiCUh
V56ypMnlrDbTGKKGW1Cnc5/JrVXasrBMWZNgBaJD6xY+9UlhFr7XO7c6tfgr
CQWn2Na/y/5IJ6qRUrauxSpmdL0jzTTuHqUjf5dvaVK58p0rxoZXG55+NaiF
UuFRJ2qW2okUYKOvgt95n80X9U8bCtTDaSmRvN/Q+nEa08DuwJao0jItMcNR
IypBFWL1kl8BxQIlR8EtA1rXgmtkjCoiQ1Sza39aPkvKmlGuzVVoaJcaSL2m
wOQnx4SI4q085J3cSetl2tQ7hy/kuBE5U67ElyXO90SZK1TBcwXR6WHDNrvr
6Nx2IVa5Aud0SjajR2gamqYm1BUh1DSNgNpEufs56HRrCA1V3dDUFXU9oWkq
YpqOFbzc0Uf/vKCaNcjErDH9aZkgq4xoNakVkAWIoNPGbw0KLSb5qbO0FmaB
uTI1+x1nlIaUVgLVbyZ9/tYNUqBJgGbYkIH/Q13KLqdZcpaDMI9EMcLl79Yh
5mm7tEous3wI7neCUHHK0udCpK0b29EpMdpwfbf0Sc6K4JE6zuhukfKsMuJZ
tJxW3bSap8aQsDyCKSktFnlnm5PRXE66mISApt9DM62fGT5r0dfUHfN+62IU
euejeKuCjofNFec0MVppmRLWLWQ21Wy4fFla/ZPLU7Ke3ip/hgTR0qaXmdDk
bzCoy2gpAtLeu2FCn/9fZ9eWZbluWzeoU90egu0xJM7KaGI7859C1k2VRORj
bzxI6VS3g3v7FAmCePEFURIlzbfbfT29t70DyzjJVlHAlPk+tJd2DFQtQMt5
co3O1ngqIec0LIbDTWXSBN7mnggkupjOP50tcCLNVhl3iFtCZbBTm0xjm2d3
b2RdsffwDxqu+1BpUzqtSj36JWGNx2IhuYloglO7mtejD/BP+b20gF6mCho9
DB+a5Ti7j+Hu015KRH03OHpX1QyjVB5VVCF9ZLgHdgoGIb6GGIIRkDKY67vK
LprSUdh2kV+WEPhSE9OmOTaHoHw90R5vABWk6sbS29wsW6K7edAUY9P5bumc
8F/4SDvOvZ7cJP86d62iTRXUWQbstZ6Z6gYfb0EsXLaZATY4h/vEdV1wfryV
smX/sIHjNXQY8Auv44Xj9cLr+MBxvPA6Bl4vnkfH3baDb8ragdN5HMk142w7
x3Ux+PKp78G7vuccF2Wi80md5nUxkDs/cZ1fuK5Tdgw4DvJt88gVtnicXzeB
tlkx52Rgt43lBt5bkkoF0daAhMZBHaPGMBNqsoVuybo6Q4ooGU+pDqsd61AQ
6g30gsXA34Rf1N9YRQCgTBUI19vB+y4dW7fK9Lv4s4HFz+JjJr6poVSkxSAG
VpQm3zRkLUtU2Nrlqi+lcgG6KlPSc3IRQyFSs3Xm+RZi4DctNwpBmhrepY19
gUufBKzrY5Vlu620i+TIiMHaHbrM+0QL9GMiODFGjnpv7OVL97KT/UtEUpVB
SmRWUzPfJhoosAkGvV0K3/PxNY1g3LXsqK5YyV68ooWe+haa7bVQJo0Dy63S
d2C7/7ZyF81NSlOGNLK5N0jyZ9nal8OvfUco8PtOnRZYMLDsuriUZmvGzgX0
OTX6oFRleq2vXPzN+lpEnYuVsEvl3rye46OC0XV+abJUiZ9PCkZhQ+hRTokk
aeNWVgQC5QNAF83ph+DbX1CoAUiXhEwGHP2RERL1fO3y1ZzNVjE2goKsdCIA
cBco9VVg5xyc0c4MTMiXZ5+VjGZK8qdk6KiQzUcUnoEdxDeIqNZmZ/qq6G4D
JwN9eSz5RJ+ULj6B9qlQ6tfGxWBwHufXiYKBqjcjIuhjJe6uHabbnQdvl+r2
5vSJ8+sL5+cnrusLmA4bBz4+fuDHzx84Xh8M5D4+8HoxqDteLxzjxTPu3HFg
AvPCnBeu88R5nvi6LnyeF99onRfmxb40/QKuC36d7OsOvbzVNh/AYNO9XtjI
PmTggcb84joP/TbL400mgHOe3KHzS/2Cu3lmhvM8Fdilg6qxbGucDn3QRoJ9
Y230qJ5oRMOUvOofJcPVgKWDaJXicOmFTV62/arzO1TgYtKTfymt4bps1dDf
Nc1UHfMQ2IV60XvVus1ZNYHCyFO+K25MGThANU4XCHsqQwuy3gKrDlQz5HbO
llfKiemKizs7xWofGn/6qU0qqaIIYuGTv9K+vBIOS1iYFwStzwVEH+eEuPXX
JOo2bnqnbP4EaXCoybz16bUxieo6ry68t0mciacq1ncziyqIl56B7BuqnhXC
nxWsru0rQi3G6yJcELZWO+xlRPeS9Flv7/AZC0hfhG2siDbvHMgp1EK2hl3x
cEr8qbFcbaO/GegJ1eOTvIiotk2IOaKD/Nrtdt2GgWqXLPbhkLBwb/3TpMMq
iZK58LfgvvltpVyB9aq06hETWfceuLEs+qMt5U1GlteAYWkPmujk7Fdt3PjW
p+gD8X46e1TV09+tHlB+XN4+bPWkCv82W9H8Ymr/tJmFqXO0Hsuizjons73J
I7RgnkGM5+3fGnFuPPsiynzy4/QSILtInS6Ks9nAI0F4HBH5GsVyRzBlUr+Q
HDpLxdw9S62bj2K+rTLZyQPmEh8Qx5TgFrS1BlQAU+0uunBIBHTiFbc1YYbx
GjgGd9OmA1fsiE2+UTvGwDHA59peL7xeL1jsvnntssW/eU34eeH6/AM4/8A8
P3On0vVmqjvg+pYrdwejBSf8uujE9GkM7OiXELW+mJNl3AF0H4CCVHcdZwLu
/p1f3K3DvNRu6iPRH/78b//Vp7IVto6+0NmaJaxRO2o+3dsYWNjfGBGE3gdc
53UrI7YRreU7+U5l4vlo3g5qmBWe3Clu6hCrEl1yhz6JRYfurMM5icj+n7x2
Pbqxxt4Vk10QLNmbTq3d+1h8EBX4e2aZhZlshKbdIhPdEiBL0KpzQUyipFnL
3nl5AVV+tiXDRv3PnEH9JXa5uj9aV6jSBpttNT2veMhPlHHn81BrhSQohd75
Kcsi3a7EpWTlexpqgCyKyTjks6zTtzvSBOUXmvxZ4QHVaOWwRrTTr34Mic84
9rfFK5Vqc8VuDoC6rTS0vGryLn80n2VSS3UGBVHY5IKTOTJAj7JVi7Az/0aw
0fowlxam4jftUvDIoh7kt3GgsgBbswJZsoydGBW8UMxpUSIGOO8Frg7eDT3D
h/x3Exn1PfzXeIkiZSrR/dIKS4LzX8rKbZHQif4oP606xtxV2pRPw9fJ2/jj
qACs09OO4gfxH3mwL+02eHlaR/44eqCtf9k3aG+4nlkWxkHFBr2dbG2cD2Ob
jSgPraptGMxyZzXrRyZuB4u4mn7AB8fEUBA1jsHdNH1yixdzDJDi+Tg2PduL
O8D8Jm/6eV68pXmdfLbtOuHz1JccWI8HkzgGLgxMBocHX5CgRGM63Cmf8nk4
BnaLnXPt54Z6MaL3N5/8Dq2NFzB0QHK8REESwHloc9y8pwsHfDrsL//+95rt
G1BGDZ1wkLILLNnW6fdmjSuMpTQ7l2g25mvg1tKxyJUvWpmLfyFvAaCq2kqW
ZQmbrTcwFDMo/QCL/Ec/hj8iG/7Qb1e0i/D4UUAUPB2bNx88vLdjG4h7wMc/
IZ++t0YX9i31mp4LOm1p8vRT9SPwjFJNmIteK9/9VnUqsNV5h+59F4vH9NsK
18VUuLDfmYtmdtkRZWstQtoPLJNuKFle0YKf/lZBlj+AkE9j4LkCIWXEr2iz
SqvLsV34fRyz3XIJKx+sbr3bs/mry1jMMdCgBxMJnbGubqMkdVd/49VXqxY7
1N3vlBUu5F/RBF/9VYUKZLNNdx8Fdu/HVQegE5aeGjt36V2hH36XaaiwKw3I
k398wTFMkK1edTtjy3qCNo6rW1fDK4QsevUfBgGa5+USU/pbyOCDv27yn/Nv
VHfZ0MFj54OZxCmRenYVur1dcvA27VBR/9SKKvUdNwUiccxJ8PT46gDZiVo7
fq1f0EyWxsG+YXrINrmH3/QlH3dgGteYEWrHkhPWaPzyFqmO9hCkH2VE6RT6
t1wEvWSX9KZvodoYGHGkTciEwQd3w0auARHssk0M/DQYz4hjwMPdOv6Ddjzd
HX4x6OILB1c8/CefVl+l38LmqQAPDJ7ieU4bvF0ac0oYqSCZgZv6jYeTtHMJ
8Latcyc2vjDhDr5xe3zwBQ1+OBZQu6XFEdj5hGNm2DPnBfvL3/4u79P5hGqQ
aqIgWAgTSNdaMCoGPFcTtML7WKueEdAXA8+fRqZEnx+f+CZsJe8JV3hkTk/t
5mfJb/Ku8do5dd4VQDxDUv0WxMLbfaeCnIxCftAV/ns5hsWgZ40tBhIWbqnG
DbOwLFyUt62+0rlgzZGiL0aRuolQQbXlRknXBMebsbYHJA12Py14RButYHtg
1NJ36FeLQflGGaApWratOlZdYoKujFx0bosqWm8S0yAqgh7VNV3St5nfFnsn
fkMsuVuQm/Qb/hZjxQRddJ61d80iUf7r7ZvBbhGuf1fBBal702G3x5ABU1J3
mnZxEBSL9lo0I7BraCXCDwu28kXY0t2+QPZgL+igxb/5ZrnQ3cdClHEwdG0s
+0uIrXoO2dGAQR1xa0DXaUtIeHjt2dKl6RnPjBlSML8I5NyZVFcQN+DyOO6E
bcBgr8av6dNaOwzjY0DBL78OswSBERTJprjbYPI5ShcmAx9BXUV9DGboAbHW
91mZtT7fxcZOBGdScpgCukNrTc4T4qtb6UA6ZZkFYrfOosfPC9e8cJ28DRs7
Z87PNWSf5sXJhAEZ0NHG1r80tfDCztlWervVxqFb/AOuoNwnvxJBC/j8nPvU
yxPUvNZa8KsSeuvVJ+WOcWB8/OS/44Nv2oqeO3YMBM0M7nz54jq54xj2V2AX
Xtoz6lBIVQK9EKeaPbeCDNNEuY2nRfi9rCHL37dE1Sva1GQb8Hd4U/oGDXQz
+8R391VA+uw7nuz/kVoLxGOfRO4OY/m99hP0AR/QFsoM7HqLx3RZ9XYOiVt4
V9rXrMhWy1KFJSfcJvDmky3bPfSkK+0rm3y5BblBGxO3trzF2ytdzhd7vUd/
FX5vo50s2N1r32EVXXZyw/POoS8m7+BJ9yXXyjK1BKUb813W5rDdfXv+HeKG
fsS91Upl+2Syc2h5OkbpjIyzvwd6lVT4nfMKrXTvUGInbZkWze4JBgxr/crT
Vvb3Nsf28gY7n3Z9dXdboCMQadCD3ixToBI87h4L0Ojcg7gcfO1P09ebgotP
FptEI5yJNseNU04EcZaPlijoarrGrucxdIvQgkEEdrxoobhoAdKYxY3F6j+U
R/5CZSBC2dK27QDmza32KElBYCRHoZNBjRKGAAy8yF5tFsFk1ATceItRNZIX
y0Tbdr2qL7XVJnd/i2Y6AzT41DluDJbg6o/ugImf04vkqHTI0TPN1sZniMpD
jBV42Thgx0s2Htlf+rowJ3f5Qg7tiWfxgjN107YybPDt3OP1E44DPvhWLI9x
En8zXBd5X9cX5nVyd/Lk7p/BYX/+2z+WR11KXClYZZVhqhU6fzqvGkiNboN9
IvCmAxG7zEjf9dsy38Iud4HoszeSHdG07Yv9BtaujtFNsrvBi+2ICe5J37oq
2v1LlqUXkm/TQUayE5dUUjR+efXSrNPLC1WLqZvuaH1AsIdLnh9Al84qNtCu
jkNuw5ewrsPCWZnQubt516hS/eIgkBxIhq0NnpMNtjbJWx/vYVkg0G0UNq9k
hd9sXOEub6ejvAYUsuBu/kid7rAHn9jp9vK78LfZd/NAz8ffHkww2X8fWG/5
HXPz4uIUpm2ptXGUX4EK7KBx5Z08u3rtGtx1I9x0egAH2zhKKSt8UVh/mLvY
19dAJ/L3uYgUmdJ1oYs+de0xUSA3Vr2LrMFdn3PulROjhX8fqtSJVPvawfLY
AQlk90jhaIPGjXxR83C1dTUzg7MYwyPn3Hhsjc/DpSQt3jO+PCFb5P0UwbPW
qh8F//BRcGRZ/YWe/7pkZ/AIW0MGgPXiPX1F3bl+xMsZ0U9J3+2NH2KjXRQE
pVDa7GFo1yYfrxHPGBc6qDfe8E7fLnNk8ytP92YQOBkEkn/87b7Trlx7ieMw
gI/zkcJtYLw+MF4vAPy0l89Z7nLoLVVf7bMD4/gBOw7S+AWTH2MH1uEwGzgv
w+WGq/VFM8c4BublmOcXzvOTt5rlIQDAnBXYlQu+gcXpezpb7RdQNNHId9hH
ZnWbDn3ovYWs+0T7zuon2gbi2Ws3qxp2h+rMWdceqixqRaYT9c4rSH/dSoDE
OlNNOPvSWmeJ9IlJkpJcA3fDFOx2CcVJofSNeW3hra3rpmpCDyCYit9k9LbF
OwSXez9s6ZzI6zmsHeTVhxIy/75l3kC3FxV8v+XxtuA3YZP3L4EmVOChi3Vo
7cb8mv0WYs7HvV5NFQ/jq5f/lrwHBpH11iHdlxY3QBN3oghduBmfLzX6wtB8
ooVFqyZhPLfFHSNk8orFpEZBsHSVR+CW+ShPfVWvnEucxgPLtiYNhOrkQt14
cPHpPAGAAVXyEo8MWIwvn1hMG6tQ/Wk8Q8coWvANWnl6wFuBklXW7OjtL/wy
BlJN4w5KD7DMMNz5PFjYaazoCj4meD7a1POfERi4OFKA+AVfHQsyWsPQf9E9
GF5RBkniDmHfrffgnRy2svRZZbKf5A5lOFtc5AumSdH7HdKnoo3+qQDQffKc
QgpjBfks+4huT4feqSMZsB11O5Y81DYjNhAMY/BcO35VYuhFD4f5lc/ZuYPP
vR0fsPFiXefYj/Zj5oL51O1YtqkdHzh+/AnjdXBHdl6wqeNR5gX3L8wvfhps
HD/hcSuWVwSYk2/lnucJ11l24TQffO5xnhfsr//xz+5bOeUNtI7dmrWhHnCA
Gogpy1tVRRvdFdVWVbbxXLvCe6CM+PmdOrbR9XR4ZZ0ZSrW+PfwMb+1wOsWW
qLzoOFlkSRWoWyZsgyRq9Rp9WqiBJr/33YFFDLGdVwYZ4rGT7xNcT/a/u89i
clpwmeIEmHiLwSRdNuqNzQK7X5769dJemri6/N72ocPOd29z7HJ/Bd2czTcL
n3+J6QYPdfc2eAfR46o/3Outem7ld/K38ODKugBxEjyQAK0dnvR7hOX+oVAA
+2A3I2S2IyjKK6W0SUWuPPFGoJjkoh56Nl9qUVcy60Rf7O3kbXxwMYzgjWWh
k0do5V7n2aHaYu33EUys/gjeqz+pe/iJb/mh9nLaetz9JGuDCcdaBEL7v8c2
LHsSE7b3uSh1qLk68uElRICicvKtskXN8IHqsp2eR07tJLE0go+hwMoURIWn
51RwZwZX0Lu8PNGmvi6XPOOZulR+ecYueCFua4tvb2FD7FhRBlAE4U+e16Yz
AMNvDUgn77S+YmM7CswMDr0VKl3pz+ifzc/xYgW5LvPPcRysOzVGD+64ufOL
Du5Tujr9MQbtBHC8Dr7pOozfctVOndvAYQPAxPz6A/71yWBtGHy84OMD5+SL
EIfO3wu/AA5cJ0zPwBn4WTHYC9NeuBy0b14Y1wn/+oTPLwaPNjEwcLx+wn7+
CV9u+DovnKcOJobOPxw8zHkM9pPpirPcYX/9z//Ofr02b3WMgGjjgirPssan
N/bGeeH9XdkNNPBv0JTbO1mH3YYi7XXe11/gyWdvQB5piF/Xs/yJAaZMVg1r
fsHroXiZICMtGY+ilCO6FqN9KtvzyE14poFakA0SsIpvUNxs1/lO2paVB8jJ
s8He9jF5ftc2QbrjfwmciVPnJ0WaL+ov67CoLLbWBv8viLqPtublOuUv1zOd
fl/cd53uCq79rpc8w9P4fNKY7XbDvMnJl71DlJMbrtVSQNAufxJfSa/Ksq1T
W148UbZ1nOlMxyzLaC5pLKrmwk0ERXGh6/5ivv5mSaa1qLegq7/9G/+Sdusr
PZ/tKhyfdVodkJx6vUztQLvLXto8ui8CvKKc4L3o6vmTZSxebWU6yVblbyj5
braL+kaegYz0Chv06gHLABzalY2+U21m/JpBuyWLZlfwyzRLM7DTBk/rH61+
bqq2uT58rf+Snla2+sjbo+48Vy1qAeRDGq0V+pFlpAvfSyYf7VGQGfZJLoMV
19lzB0y7kgbUaqS+YXHMSwRmcFzXha/P/wXMMMZL32Zl0DfGgOlTYfmVEg+L
1K3cAUzg/ATOP7jDp0+I+fiB8fMnbLx45p3HN2ENY06cf/wPrs8/+JZqnrn3
wrQDE8BxGHcQz0/Y/IT5qVvDDGi/vhxz/MDUkSc0nGf0uTvPt9PbtHx20WiP
Af8HVLtKcKK2nJUAAAAASUVORK5CYII=
" alt="Hugues, Caro, Sacha et Jules" style="display:block!important;width:100%!important;max-width:630px!important;height:auto!important;max-height:150px!important;object-fit:contain!important;object-position:center!important"></div><button class="voice-top" onclick="voiceGeneral()"><span class="mic">🎙</span><span><b>Parler à HAVOO</b><small>Dicter une tâche, une course, une idée…</small></span></button><button class="weather-card" onclick="weatherModal()"><div class="weather-main"><span class="sun">☀️</span><div><span>Namur</span><strong>18°C</strong></div></div><div class="weather-strip"><div>Auj.<br>☀ 24°</div><div>Jeu.<br>⛅ 22°</div><div>Ven.<br>🌦 20°</div><div>Sam.<br>☀ 23°</div><div>Dim.<br>☁ 19°</div></div></button><div class="clockbox"><div class="time" id="clock">${new Date().toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})}</div><div class="date">${new Date().toLocaleDateString('fr-BE',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div></header><section class="dashboard"><article class="card agenda"><div class="card-inner"><div class="titlebar"><span class="iconbox">▣</span><h2>Agenda familial</h2><div class="agenda-tools"><button onclick="openCalendar('day')">Jour</button><button class="active" onclick="openCalendar('week')">Semaine</button><button onclick="openCalendar('month')">Mois</button><button class="plus" onclick="event.stopPropagation();eventForm()">＋</button></div></div><div class="week-grid">${dashboardWeek()}</div></div></article><article class="card tasks"><div class="card-inner"><div class="titlebar"><span class="iconbox">✓</span><h2>Tâches</h2><span class="grow"></span><button class="plus" onclick="tasksPeople()">＋</button></div><div class="task-filter">${['Tous','Hugues','Caro','Sacha','Jules'].map((n,i)=>`<button class="${i===0?'active':''}" onclick="showTasks('${n}')">${n}</button>`).join('')}</div><div id="taskRows">${taskRows('Tous')}</div></div></article><article class="card messages"><div class="card-inner"><div class="titlebar"><span class="iconbox">🎧</span><h2>Messages</h2></div><button class="message-new" onclick="messageComposer()">🎙 Nouveau message</button><div>${data.messages.length?data.messages.slice(-4).reverse().map(messageCard).join(''):`<div class="shopping-empty"><div><div style="font-size:38px">💬</div><strong>Aucun message</strong><p>Laisse un message à quelqu’un de la famille.</p></div></div>`}</div></div></article><article class="card shopping"><div class="card-inner"><div class="titlebar"><span class="iconbox">🛒</span><h2>Liste de courses</h2><span class="grow"></span><button class="plus" onclick="shopModal()">＋</button></div>${data.groceries.length?`<div>${data.groceries.slice(0,8).map((x,i)=>`<div class="task-row"><span class="check"></span><span>${esc(x)}</span><button onclick="removeShop(${i})">✕</button></div>`).join('')}</div>`:`<div class="shopping-empty"><div><div class="cart">🛒</div><strong>La liste est vide</strong><p>Ajoute uniquement ce qu'il faut acheter.</p><button class="add-shop" onclick="shopModal()">＋ Ajouter</button></div></div>`}</div></article><article class="card menu"><div class="card-inner"><div class="titlebar"><span class="iconbox">🍴</span><h2>Menu de la semaine</h2></div>${data.meals.map((m,i)=>`<div class="meal-row"><b>${m[0]}</b><span>${esc(m[1])}</span><button class="meal-mic" onclick="editMeal(${i})">🎙</button></div>`).join('')}</div></article><article class="card recipes"><div class="card-inner"><div class="titlebar"><span class="iconbox">♨</span><h2>Idée recette</h2></div><div class="recipe-main"><img src="${r.img}" onclick="recipeModal('${r.id}')"><div class="recipe-body"><h3>${r.title}</h3><div class="recipe-meta">◷ ${r.time}</div><p>${r.desc}</p><div class="recipe-actions"><button onclick="likeRecipe('${r.id}')">👍</button><button onclick="dismissRecipe('${r.id}')">👎</button></div><button class="recipe-add" onclick="addRecipe('${r.id}')">＋ Ajouter aux courses</button></div></div></div></article></section></main>`}function taskRows(who){return data.tasks.filter(t=>!t.done&&(who==='Tous'||t.who===who)).map(t=>`<div class="task-row"><button class="check" onclick="doneTask(${t.id})"></button><span>${esc(t.title)}</span><span class="owner ${members[t.who].short}">${t.who}</span></div>`).join('')||'<div class="shopping-empty"><div>Aucune tâche</div></div>'}function showTasks(w){$('#taskRows').innerHTML=taskRows(w);document.querySelectorAll('.task-filter button').forEach(b=>b.classList.toggle('active',b.textContent===w))}function doneTask(id){let t=data.tasks.find(x=>x.id===id);if(t)t.done=true;save();render()}function messageCard(m){return `<div class="message-card"><div class="for">Pour ${esc(m.to)}</div><div class="when">${m.sendAt?'Prévu : '+new Date(m.sendAt).toLocaleString('fr-BE'):'Maintenant'}</div><div class="bubble">${esc(m.text||'🎙 Message vocal')}</div></div>`}function overlay(inner,small=true){document.body.insertAdjacentHTML('beforeend',`<div class="panel-overlay" onclick="if(event.target===this)closePanel()"><section class="panel ${small?'small':''}">${inner}</section></div>`)}function closePanel(){$('.panel-overlay')?.remove()}function weatherModal(){overlay(`<div class="panel-head"><h1>Météo · Namur</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="forecast">${[['Aujourd’hui','☀️','18° / 24°'],['Demain','⛅','16° / 22°'],['Vendredi','🌦','14° / 20°'],['Samedi','☀️','15° / 23°'],['Dimanche','☁️','13° / 19°']].map(x=>`<div><b>${x[0]}</b><div class="ico">${x[1]}</div><strong>${x[2]}</strong></div>`).join('')}</div>`)}function openCalendar(view='week',focus=today){let body=view==='week'?fullWeek(focus):view==='month'?monthView(focus):dayView(focus);overlay(`<div class="panel-head"><div><h1>Agenda familial</h1><div class="muted">${new Intl.DateTimeFormat('fr-BE',{month:'long',year:'numeric'}).format(new Date(focus+'T12:00:00'))}</div></div><span class="grow"></span><button onclick="eventForm('${focus}')">＋</button><button onclick="closePanel()">✕</button></div><div class="tabs"><button class="${view==='day'?'active':''}" onclick="swapCal('day','${focus}')">Jour</button><button class="${view==='week'?'active':''}" onclick="swapCal('week','${focus}')">Semaine</button><button class="${view==='month'?'active':''}" onclick="swapCal('month','${focus}')">Mois</button></div>${body}`,false)}function swapCal(v,f){closePanel();openCalendar(v,f)}function fullWeek(f){let s=weekStart(f),h='<div class="week-grid" style="height:62vh">';for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i);let di=iso(d);h+=`<div class="daycol ${di===today?'today':''}" onclick="swapCal('day','${di}')"><div class="dayhead"><b>${new Intl.DateTimeFormat('fr-BE',{weekday:'long'}).format(d)}</b><strong>${d.getDate()}</strong></div>${eventsOn(di).map(e=>`<div class="event"><span class="event-dot" style="background:${eventColor(e)}"></span><span class="time">${e.time||''}</span><span class="label">${esc(e.title)}</span></div>`).join('')}</div>`}return h+'</div>'}function dayView(f){return `<h2>${new Intl.DateTimeFormat('fr-BE',{weekday:'long',day:'numeric',month:'long'}).format(new Date(f+'T12:00:00'))}</h2>${eventsOn(f).map(e=>`<div class="message-card"><b>${e.time||'Toute la journée'} · ${esc(e.title)}</b><div class="muted">${e.who.join(', ')}</div></div>`).join('')||'<div class="shopping-empty"><div>Rien de prévu</div></div>'}`}function monthView(f){let d=new Date(f+'T12:00:00'),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,n=new Date(y,m+1,0).getDate(),h='<div style="display:grid;grid-template-columns:repeat(7,1fr);gap:6px">';for(let i=0;i<start;i++)h+='<div></div>';for(let x=1;x<=n;x++){let di=iso(new Date(y,m,x));h+=`<button style="min-height:70px;border:1px solid #dce4ef;border-radius:10px;background:#fff;text-align:left;padding:7px" onclick="swapCal('day','${di}')"><b>${x}</b><div>${eventsOn(di).slice(0,3).map(e=>`<span class="event-dot" style="display:inline-block;background:${eventColor(e)}"></span>`).join('')}</div></button>`}return h+'</div>'}function eventForm(date=today){closePanel();overlay(`<div class="panel-head"><h1>Ajouter à l'agenda</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="form-grid"><select id="etype"><option value="event">Rendez-vous</option><option value="birthday">Anniversaire</option></select><input id="etitle" placeholder="Titre / prénom"><input id="edate" type="date" value="${date}"><input id="etime" type="time"><select id="ewho"><option>Hugues</option><option>Caro</option><option>Sacha</option><option>Jules</option><option>Famille</option></select><button class="primary" onclick="saveEvent()">Ajouter</button></div>`)}function saveEvent(){let type=$('#etype').value,title=$('#etitle').value.trim(),date=$('#edate').value;if(!title||!date)return;if(type==='birthday')data.birthdays.push({id:Date.now(),name:title,date});else{let w=$('#ewho').value;data.events.push({id:Date.now(),date,time:$('#etime').value,title,who:w==='Famille'?['Hugues','Caro','Sacha','Jules']:[w]})}save();closePanel();render()}function tasksPeople(){overlay(`<div class="panel-head"><h1>Tâches par personne</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="people-grid">${['Hugues','Caro','Sacha','Jules'].map(n=>`<button onclick="taskForm('${n}')">${n}</button>`).join('')}</div>`)}function taskForm(w){closePanel();overlay(`<div class="panel-head"><h1>Nouvelle tâche · ${w}</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="form-grid"><input id="newtask" style="grid-column:1/-1" placeholder="Que faut-il faire ?"><button class="primary" onclick="addTask('${w}')">Ajouter</button></div>`)}function addTask(w){let v=$('#newtask').value.trim();if(!v)return;data.tasks.push({id:Date.now(),title:v,who:w,done:false});save();closePanel();render()}function shopModal(){overlay(`<div class="panel-head"><h1>Liste de courses</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="form-grid"><input id="shop" style="grid-column:1/-1" placeholder="Ex. lait"><button class="primary" onclick="addShop()">Ajouter</button></div><div>${data.groceries.map((x,i)=>`<div class="task-row"><span>${esc(x)}</span><button onclick="removeShop(${i})">✕</button></div>`).join('')}</div>`)}function addShop(){let v=$('#shop').value.trim();if(!v)return;data.groceries.push(v);save();closePanel();render()}function removeShop(i){data.groceries.splice(i,1);save();render();closePanel()}function editMeal(i){overlay(`<div class="panel-head"><h1>${data.meals[i][0]}</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="form-grid"><input id="mealtext" style="grid-column:1/-1" value="${esc(data.meals[i][1])}"><button onclick="dictateTo('mealtext')">🎙 Dicter</button><button class="primary" onclick="saveMeal(${i})">Enregistrer</button></div>`)}function saveMeal(i){data.meals[i][1]=$('#mealtext').value.trim();save();closePanel();render()}function recipeModal(id){let r=recipes.find(x=>x.id===id);overlay(`<div class="panel-head"><h1>${r.title}</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><img src="${r.img}" style="width:100%;height:240px;object-fit:cover;border-radius:15px"><h3>Ingrédients</h3>${r.ings.map(x=>`<div class="task-row"><span>${x}</span></div>`).join('')}<button class="primary" style="width:100%;padding:11px;margin-top:10px" onclick="addRecipe('${id}')">Ajouter les ingrédients aux courses</button>`)}function addRecipe(id){recipes.find(x=>x.id===id).ings.forEach(x=>data.groceries.push(x));save();closePanel();render()}function likeRecipe(id){if(!data.favorites.includes(id))data.favorites.push(id);save()}function dismissRecipe(id){if(!data.dismissed.includes(id))data.dismissed.push(id);save();render()}function messageComposer(){overlay(`<div class="panel-head"><h1>Nouveau message</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><b>1. Pour qui ?</b><div class="recipient-grid" id="recips">${['Toute la famille','Hugues','Caro','Sacha','Jules'].map(n=>`<button onclick="pickRecipient(this,'${n}')">${n}</button>`).join('')}</div><b>2. Quand ?</b><div class="form-grid" style="margin-top:7px"><input id="mdate" type="date"><input id="mtime" type="time"><textarea id="mtext" placeholder="Écris ou dicte le message…"></textarea></div><div class="record-controls"><button onclick="dictateTo('mtext')">🎙 Dicter</button><button onclick="startRecording()">● Enregistrer</button><button onclick="resetMessage()">↻ Recommencer</button></div><p class="muted">Sans date ni heure, le message est disponible immédiatement.</p><button class="primary" style="width:100%;padding:11px" onclick="sendMessage()">Envoyer / programmer</button>`)}let selectedRecipient='',recorded=false;function pickRecipient(el,n){selectedRecipient=n;document.querySelectorAll('#recips button').forEach(b=>b.classList.remove('active'));el.classList.add('active')}function resetMessage(){$('#mtext').value='';$('#mdate').value='';$('#mtime').value='';recorded=false}function sendMessage(){if(!selectedRecipient)return alert('Choisis d’abord le destinataire.');let text=$('#mtext').value.trim();if(!text&&!recorded)return alert('Ajoute un message.');let d=$('#mdate').value,t=$('#mtime').value,sendAt=d?`${d}T${t||'00:00'}`:'';data.messages.push({id:Date.now(),to:selectedRecipient,text:text||(recorded?'🎙 Message vocal':''),sendAt});save();closePanel();render()}function voiceGeneral(){overlay(`<div class="panel-head"><h1>Parler à HAVOO</h1><span class="grow"></span><button onclick="closePanel()">✕</button></div><div class="form-grid"><textarea id="generalVoice" placeholder="Ex. Ajoute du lait aux courses"></textarea><button onclick="dictateTo('generalVoice')">🎙 Dicter</button><button class="primary" onclick="applyGeneral()">Valider</button></div>`)}function applyGeneral(){let v=$('#generalVoice').value.trim();if(!v)return;let l=v.toLowerCase();if(l.includes('course'))data.groceries.push(v.replace(/.*courses?/i,'').trim()||v);else data.tasks.push({id:Date.now(),title:v,who:'Hugues',done:false});save();closePanel();render()}function dictateTo(id){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('La dictée vocale n’est pas disponible ici.');let r=new SR();r.lang='fr-BE';r.onresult=e=>$('#'+id).value=e.results[0][0].transcript;r.start()}async function startRecording(){try{await navigator.mediaDevices.getUserMedia({audio:true});recorded=true;alert('Micro autorisé. Pour le prototype, le message vocal est marqué comme enregistré. La sauvegarde audio complète viendra avec le stockage en ligne.')}catch{alert('Autorise le microphone.')}}render();setInterval(()=>{if($('#clock'))$('#clock').textContent=new Date().toLocaleTimeString('fr-BE',{hour:'2-digit',minute:'2-digit'})},15000);